[package]
name = "tabreport_client"
version = "0.1.0"
authors = ["Diego Veralli <diegoov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbus = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"

[dependencies.tabreport-common]
path = "../common"
