#!/usr/bin/env python3

import os
import sys
import json

binary_path = sys.argv[1]

template = os.path.join(os.path.dirname(__file__),
                        'net.diegoveralli.tabreport.json')

with open(template, 'r', encoding='utf-8') as f:
    values = json.load(f)
    values['path'] = binary_path
    print(json.dumps(values, indent=2))
