[package]
name = "tabreport-common"
version = "0.1.6"
authors = ["Diego Veralli <tabreport@diegoveralli.net>"]
edition = "2018"

[dependencies]
serde = { version = "1.*", features = ["derive"] }
serde_json = "1.*"
