name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: abbbi/github-actions-tune@0b48641ceb645d4ad4573b0d17b770d85770f9c7
    - run: rustup component add rustfmt
    - run: rustup component add clippy
    - run: sudo apt-get install -y --no-install-recommends libdbus-1-dev jq python3 python3-pip
    - run: pip3 install --user 'yq==2.12.*'
    - run: mkdir -p ~/.local/bin/
    - name: Build
      run: ./build.sh check
    - name: Native extension install check
      run: ./install_native.sh
